version: 1.1

stages:
  - stage:
      - git-checkout:
          params:
            depth: 1

  - stage:
      - buildpack:
          alias: demo
          params:
            context: ${git-checkout}
            modules:
              - name: demo
                path: demo-server

  - stage:
      - release:
          version: 1.0
          params:
            dice_yml: ${git-checkout}/dice.yml
            docker_images: ${maven-pack}/docker_image
            replacement_images:
              - ${demo}/pack-result

  - stage:
      - dice:
          params:
            release_id_path: ${release}